tasks:

  - source: tasks/retrieve.py
    product:
      nb: "products/retrieve.ipynb"
      data: "{{folder_output}}/params.txt"

    params:
      folder_output: "{{folder_output}}"    
      solr_api_url: "{{solr_api_url}}"   
      solr_api_key: "{{solr_api_key}}"   
      query: "{{query}}"

  - source: tasks/retrieve_templates.py
    product:
      nb: "products/retrieve_templates.ipynb"
      data: "{{folder_output}}/templates"

    params:
      folder_output: "{{folder_output}}"    
      templates_pchem: "{{templates_pchem}}"   

  - source: tasks/match_params.py
    product:
      nb: "products/match_params.ipynb"
      data: "{{folder_output}}/terms/matched_params.txt"

    params:
      folder_output: "{{folder_output}}"      

  - source: tasks/onto.py
    product:
      nb: "products/onto.ipynb"
      data: "{{folder_output}}/terms"      

    params:
      folder_output: "{{folder_output}}"    
      
 




