tasks:

  - source: tasks/retrieve.py
    product:
      nb: "products/retrieve.ipynb"
      data: "{{folder_output}}/params.txt"

    params:
      folder_output: "{{folder_output}}"    
      solr_api_url: "{{solr_api_url}}"   
      solr_api_key: "{{solr_api_key}}"   
      query: "{{query}}"

  - source: tasks/retrieve_templates.py
    product:
      nb: "products/retrieve_templates.ipynb"
      data: "{{folder_output}}/templates"

    params:
      folder_output: "{{folder_output}}"    
      templates_pchem: "{{templates_pchem}}"   

  - source: tasks/match_params.py
    product:
      nb: "products/match_params.ipynb"
      data: "{{folder_output}}/terms/matched_params.txt"

    params:
      folder_output: "{{folder_output}}"      

  - source: tasks/onto.py
    product:
      nb: "products/onto.ipynb"
      data: "{{folder_output}}/terms"      

    params:
      folder_output: "{{folder_output}}"
      blueprint: "{{blueprint}}"    
      model_embedding: "{{model_embedding}}"
      hnsw_distance: "{{hnsw_distance}}"            

  - source: tasks/onto_stats.py
    product:
      nb: "products/onto_stats.ipynb"

    params:
      folder_output: "{{folder_output}}"
      model_embedding: "{{model_embedding}}"
      hnsw_distance: "{{hnsw_distance}}"  

  - source: tasks/spacy.py
    product:
      nb: "products/spacy.ipynb"

    params:
      folder_output: "{{folder_output}}"
       

  - source: tasks/overview.py
    product:
      nb: "products/overview.ipynb"     

    params:
      folder_output: "{{folder_output}}" 
      solr_api_url: "{{solr_api_url}}"   
      solr_api_key: "{{solr_api_key}}"     
      annotation_folder: "{{annotation_folder}}"  
      query: "{{query}}"        
      
  - source: tasks/blueprint.py
    product:
      nb: "products/blueprint.ipynb"  
      data: "{{folder_output}}/terms/blueprint.json"   

    params:
      folder_output: "{{folder_output}}" 
      blueprint: "{{blueprint}}"       
 




